# Final Project
# CS 111, Reckinger
# Leen Alhejoj

import turtle
import random
from tkinter import *
from tkinter import ttk

screen = turtle.getscreen()
t = turtle.Turtle()

screen.bgpic("motorolalegends.gif")

companylogo = turtle.Turtle()
turtle.addshape("logo.gif")
companylogo.penup()
companylogo.shape("logo.gif")
companylogo.hideturtle()
companylogo.goto(0, 600)
companylogo.showturtle()
companylogo.speed("slowest")
companylogo.goto(0, 160)

texts = turtle.Turtle()
texts.penup()
texts.hideturtle()
texts.goto(0, -170)
texts.color("darkblue")
texts.write("Enter Your Name: ", False, align='center', font=('Arial', 30, 'bold'))
name = turtle.textinput("Name","Enter Your Name: ")
texts.clear()
screen.clear()
screen.bgcolor("white")
file = open("feature_data.txt")
data = file.readlines()
print(data)
formattext = turtle.Turtle()
formattext.penup()
formattext.goto(0, 250)
formattext.color("darkblue")
formattext.pendown()
formattext.write("Hello" " "+name.capitalize() + "!", False, align='center', font=('Arial', 20, 'bold'))
formattext.penup()
formattext.goto(0, 200)
formattext.color("darkblue")
formattext.pendown()
formattext.write("These are the features available on the dashboard:", False, align='center', font=('timesnewroman', 15, 'bold'))
formattext.penup()
formattext.goto(0, 150)
formattext.color("darkblue")
formattext.pendown()
formattext.write("1 - Upcoming training", False, align='center', font=('timesnewroman', 15, 'bold'))
formattext.penup()
formattext.goto(0, 100)
formattext.color("darkblue")
formattext.pendown()
formattext.write("2 - Required courses more information", False, align='center', font=('timesnewroman', 15, 'bold'))
formattext.penup()
formattext.goto(0, 50)
formattext.color("darkblue")
formattext.pendown()
formattext.write("3 - Emails", False, align='center', font=('timesnewroman', 15, 'bold'))
formattext.penup()
formattext.goto(0, 0)
formattext.color("darkblue")
formattext.pendown()
formattext.write("4 - Your training Course ", False, align='center', font=('timesnewroman', 15, 'bold'))
formattext.hideturtle()
start_button = turtle.Turtle()
turtle.addshape("button.gif")
start_button.penup()
start_button.shape("button.gif")
start_button.hideturtle()
start_button.goto(0, -170)
start_button.showturtle()

def coursemap1(x,y):
  screen.clearscreen()
  screen.bgpic("coursemap.gif")
  panda = turtle.Turtle()
  panda.hideturtle()
  turtle.addshape("panda1.gif")
  panda.hideturtle()
  panda.penup()
  panda.shape("panda1.gif")
  panda.hideturtle()
  panda.goto(-250,-100)
  panda.showturtle()
  intropanda = turtle.Turtle()
  intropanda.penup()
  intropanda.hideturtle()
  intropanda.goto(0, 300)
  intropanda.color("black")
  intropanda.write("Click on the pandalf to continue the course.", False, align='center', font=('Arial', 15, 'bold'))
  panda.onclick(slide2)

def coursemap2(x,y):
  screen.clearscreen()
  screen.bgpic("coursemap.gif")
  panda = turtle.Turtle()
  turtle.addshape("panda2.gif")
  panda.penup()
  panda.shape("panda2.gif")
  panda.hideturtle()
  panda.goto(39,170)
  panda.showturtle()
  intropanda = turtle.Turtle()
  intropanda.penup()
  intropanda.hideturtle()
  intropanda.goto(0, 300)
  intropanda.color("black")
  intropanda.write("Click on the pandalf to continue the course.", False, align='center', font=('Arial', 15, 'bold'))
  panda.onclick(slide3)

def coursemap3(x,y):
  screen.clearscreen()
  screen.bgpic("coursemap.gif")
  panda = turtle.Turtle()
  turtle.addshape("panda3.gif")
  panda.penup()
  panda.shape("panda3.gif")
  panda.hideturtle()
  panda.goto(350, 80)
  panda.showturtle()
  intropanda = turtle.Turtle()
  intropanda.penup()
  intropanda.hideturtle()
  intropanda.goto(0, 300)
  intropanda.color("black")
  intropanda.write("Click on the pandalf to continue the course.", False, align='center', font=('Arial', 15, 'bold'))
  panda.onclick(slide4)

def coursemap4(x,y):
  screen.clearscreen()
  screen.bgpic("coursemap.gif")
  panda = turtle.Turtle()
  turtle.addshape("panda4.gif")
  panda.penup()
  panda.shape("panda4.gif")
  panda.hideturtle()
  panda.goto(0, -200)
  panda.showturtle()
  intropanda = turtle.Turtle()
  intropanda.penup()
  intropanda.hideturtle()
  intropanda.goto(0, 300)
  intropanda.color("black")
  intropanda.write("Click on the pandalf to finish the course.", False, align='center', font=('Arial', 15, 'bold'))
  panda.onclick(slide5)

def slide1(x,y):
  screen.clearscreen()
  screen.bgpic("courseslide1.gif")
  nextbutton = turtle.Turtle()
  turtle.addshape("nextbutton.gif") 
  nextbutton.penup()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(250,-220)
  nextbutton.showturtle()
  nextbutton.onclick(coursemap1)

def slide2(x,y):
  screen.clearscreen()
  screen.bgpic("slide2.gif")
  nextbutton = turtle.Turtle()
  nextbutton.hideturtle()
  turtle.addshape("nextbutton.gif") 
  nextbutton = turtle.Turtle()
  nextbutton.penup()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(260,-230)
  nextbutton.showturtle()
  nextbutton.onclick(coursemap2)

def slide3(x,y):
  screen.clearscreen()
  screen.bgpic("slide3.gif")
  nextbutton = turtle.Turtle()
  turtle.addshape("nextbutton.gif") 
  nextbutton.penup()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(260,-230)
  nextbutton.showturtle()
  nextbutton.onclick(coursemap3)

def slide4(x,y):
  screen.clearscreen()
  screen.bgpic("slides4.gif")
  nextbutton = turtle.Turtle()
  nextbutton.hideturtle()
  turtle.addshape("nextbutton.gif") 
  nextbutton.hideturtle()
  nextbutton.penup()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(350,-230)
  nextbutton.showturtle()
  nextbutton.onclick(coursemap4)

def slide5(x,y):
  screen.clearscreen()
  screen.bgpic("coursedone.gif")
  nextbutton = turtle.Turtle()
  nextbutton.hideturtle() 
  turtle.addshape("nextbutton.gif") 
  nextbutton.penup()
  nextbutton.hideturtle()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(250,-220)
  nextbutton.showturtle()
  nextbutton.onclick(quiz)

def quiz(x,y):
  screen.clearscreen()
  screen.bgpic("quiz.gif")
  nextbutton = turtle.Turtle()
  turtle.addshape("nextbutton.gif") 
  nextbutton.penup()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(250,-220)
  nextbutton.showturtle()
  nextbutton.onclick(question1)

def message(x,y):
  screen.clearscreen()
  screen.bgpic("message.gif")
  returns = turtle.Turtle()
  returns.hideturtle()
  turtle.addshape("returnbutton1.gif")
  returns.penup()
  returns.shape("returnbutton1.gif")
  returns.hideturtle()
  returns.goto(300, -290)
  returns.showturtle()
  returns.onclick(questmap)

def questmapunique(x,y):
  screen.clearscreen()
  screen.bgpic("Questmap.gif")
  screen.bgcolor("white")
  newtext1 = turtle.Turtle()
  newtext1.penup()
  newtext1.hideturtle()
  newtext1.goto(-250, 200)
  newtext1.color("black")
  newtext1.write("Motorola Legends Dashboard", False, align='center', font=('Arial', 15, 'bold'))
  maplegend = turtle.Turtle()
  maplegend.hideturtle()
  turtle.addshape("number11.gif")
  maplegend.penup()
  maplegend.shape("number11.gif")
  maplegend.hideturtle()
  maplegend.goto(-390, -230)
  maplegend.showturtle()
  pandalf = turtle.Turtle()
  pandalf.hideturtle()
  turtle.addshape("panda4.gif")
  pandalf.penup()
  pandalf.shape("panda4.gif")
  pandalf.hideturtle()
  pandalf.goto(390, 230)
  pandalf.showturtle()
  emailnotif = turtle.Turtle()
  emailnotif.hideturtle()
  turtle.addshape("emailnotif.gif")
  emailnotif.penup()
  emailnotif.shape("emailnotif.gif")
  emailnotif.hideturtle()
  emailnotif.goto(250, 250)
  emailnotif.showturtle()
  emailnotif.onclick(message)
  level_list =["button1.gif", "button2.gif", "button3.gif", "button4.gif"]
  maplevels = []
  yaxis = [30, -110, -10, 65]
  x = -200
  for i in range(len(level_list)):
    turtle.addshape(level_list[i])
    quest = turtle.Turtle()
    quest.hideturtle()
    maplevels.append(quest)
    quest.shape(level_list[i])
    quest.penup()
    quest.goto(x, yaxis[i])
    quest.showturtle()
    x = x + 120
  while True:
    maplevels[0].onclick(choose1)
    maplevels[1].onclick(choose2)
    maplevels[2].onclick(choose3)
    maplevels[3].onclick(choose4)

def incorrect():
  screen.clearscreen()
  screen.bgpic("wrong.gif")
  startcourse = turtle.Turtle()
  turtle.addshape("continuebutton.gif")
  startcourse.penup()
  startcourse.shape("continuebutton.gif")
  startcourse.hideturtle()
  startcourse.goto(200, -200)
  startcourse.showturtle()
  startcourse.onclick(choose4)

def correct():
  screen.clearscreen()
  screen.bgpic("finishcourse.gif")
  returns = turtle.Turtle()
  returns.hideturtle()
  turtle.addshape("returnbutton1.gif")
  returns.penup()
  returns.shape("returnbutton1.gif")
  returns.hideturtle()
  returns.goto(300, -250)
  returns.showturtle()
  returns.onclick(questmapunique)

def question2(x,y):
  screen.clearscreen()
  screen.bgpic("question2.gif")
  answer = turtle.textinput("Question2", "Enter '1' or '2': ")
  if answer == '1':
    correct()
  if answer == '2':
    incorrect()
  while answer != '1' or '2':
    answer = input("Enter '1' or '2': ")
    if answer == '1':
      correct()
    if answer == '2':
      incorrect()

def question1(x,y):
  screen.clearscreen()
  screen.bgpic("question1.gif")
  answer = turtle.textinput("Question 1", "Enter '1' or '2': ")
  if answer == '1':
    print("Incorrect")
  if answer == '2':
    print("Correct")
  nextbutton = turtle.Turtle()
  turtle.addshape("nextbutton.gif") 
  nextbutton.hideturtle()
  nextbutton.penup()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(250,-220)
  nextbutton.showturtle()
  nextbutton.onclick(question2)

def course1(x,y):
  screen.clearscreen()
  screen.bgpic("trainingcourse.gif")
  nextbutton = turtle.Turtle()
  turtle.addshape("nextbutton.gif") 
  nextbutton.penup()
  nextbutton.shape("nextbutton.gif")
  nextbutton.hideturtle()
  nextbutton.goto(250,-220)
  nextbutton.showturtle()
  nextbutton.onclick(slide1)


def coursemap(x,y):
  screen.clearscreen()
  screen.bgpic("coursemap.gif")
  panda = turtle.Turtle()
  turtle.addshape("panda.gif")
  panda.penup()
  panda.shape("panda.gif")
  panda.hideturtle()
  panda.goto(-350,150)
  panda.showturtle()
  intropanda = turtle.Turtle()
  intropanda.penup()
  intropanda.hideturtle()
  intropanda.goto(0, 300)
  intropanda.color("black")
  intropanda.write("Click on the pandalf to start the course.", False, align='center', font=('Arial', 15, 'bold'))
  panda.onclick(course1)

def course_start(x,y):
  screen.clearscreen()
  screen.bgpic("newest.gif")
  startcourse = turtle.Turtle()
  turtle.addshape("continuebutton.gif")
  startcourse.penup()
  startcourse.shape("continuebutton.gif")
  startcourse.hideturtle()
  startcourse.goto(200, 50)
  startcourse.showturtle()
  startcourse.onclick(coursemap)

def boxpopup(x,y):
  screen.clearscreen()
  txt1 = turtle.textinput("Email", "Compose: ")
  t.color("black")
  box = Tk()
  box.geometry("600x250")
  box_email = Label(box, text="Your Email Has Been Sent!", font=("timesnewroman 20 underline"))
  box_email.pack()
  box1 = turtle.Turtle()
  turtle.addshape("returnbutton1.gif")
  box1.penup()
  box1.shape("returnbutton1.gif")
  box1.hideturtle()
  box1.goto(250, 50)
  box1.showturtle()
  box1.onclick(questmap)
  screen.bgpic("emailsent.gif")

def emails(x,y):
  screen.clearscreen()
  screen.bgpic("emailpicture.gif")
  startcourse = turtle.Turtle()
  turtle.addshape("continuebutton.gif")
  startcourse.penup()
  startcourse.shape("continuebutton.gif")
  startcourse.hideturtle()
  startcourse.goto(200, -150)
  startcourse.showturtle()
  startcourse.onclick(boxpopup)

def choose1(x, y):
  choice1 = turtle.Turtle()
  choice1.hideturtle()
  screen.clearscreen()
  screen.bgpic("motorolaschedule.gif")
  box1 = turtle.Turtle()
  box1.hideturtle()
  turtle.addshape("returnbutton1.gif")
  box1.hideturtle()
  box1.penup()
  box1.shape("returnbutton1.gif")
  box1.hideturtle()
  box1.goto(-200, 250)
  box1.showturtle()
  box1.onclick(questmap)
  note = turtle.Turtle()
  note.penup()
  note.hideturtle()
  note.goto(120, 230)
  note.color("black")
  note.write("Courses you need to take: ", False, align='center', font=('Arial', 15, 'bold'))
  monday = turtle.Turtle()
  monday.penup()
  monday.hideturtle()
  monday.goto(130, 140)
  monday.color("black")
  monday.write("Emergency Response Training", False, align='center', font=('Arial', 15, 'bold'))
  tuesday = turtle.Turtle()
  tuesday.penup()
  tuesday.hideturtle()
  tuesday.goto(130, 60)
  tuesday.color("black")
  tuesday.write("Personal Security Training", False, align='center', font=('Arial', 15, 'bold'))
  wednesday = turtle.Turtle()
  wednesday.penup()
  wednesday.hideturtle()
  wednesday.goto(130, -30)
  wednesday.color("black")
  wednesday.write("Data Privacy", False, align='center', font=('Arial', 15, 'bold'))
  thursday = turtle.Turtle()
  thursday.penup()
  thursday.hideturtle()
  thursday.goto(130, -120)
  thursday.color("black")
  thursday.write("Records Management", False, align='center', font=('Arial', 15, 'bold'))
  friday = turtle.Turtle()
  friday.penup()
  friday.hideturtle()
  friday.goto(130, -220)
  friday.color("black")
  friday.write("Cultural Competence", False, align='center', font=('Arial', 15, 'bold'))
  saturday = turtle.Turtle()
  saturday.penup()
  saturday.hideturtle()
  saturday.goto(130, -300)
  saturday.color("black")
  saturday.write("Business Ethics", False, align='center', font=('Arial', 15, 'bold'))

def searchinput2(x,y):
  screen.clearscreen()
  choice2 = turtle.Turtle()
  choice2.showturtle()
  screen.clearscreen()
  screen.bgpic("Search22.gif")
  search = turtle.Turtle()
  turtle.addshape("searchbar1.gif")
  search.penup()
  search.shape("searchbar1.gif")
  search.goto(0, 50)
  search.showturtle()
  search.onclick(searchinput)
  returns = turtle.Turtle()
  returns.hideturtle()
  turtle.addshape("returnbutton1.gif")
  returns.hideturtle()
  returns.penup()
  returns.shape("returnbutton1.gif")
  returns.hideturtle()
  returns.goto(300, -250)
  returns.showturtle()
  returns.onclick(questmap)

def searchinput(x,y):
  txt1 = turtle.textinput("Course Search", "Course Number: ")
  t.color("black")
  if txt1 == "1":
    screen.clearscreen()
    screen.bgpic("11.gif")
    returns = turtle.Turtle()
    returns.hideturtle()
    turtle.addshape("returnbutton1.gif")
    returns.penup()
    returns.shape("returnbutton1.gif")
    returns.hideturtle()
    returns.goto(-300, -250)
    returns.showturtle()
    returns.onclick(questmap)
    searchC = turtle.Turtle()
    searchC.hideturtle()
    turtle.addshape("SearchC.gif")
    searchC.penup()
    searchC.shape("SearchC.gif")
    searchC.hideturtle()
    searchC.goto(300, -250)
    searchC.showturtle()
    searchC.onclick(searchinput2)
  if txt1 == "2":
    screen.clearscreen()
    screen.bgpic("12.gif")
    returns = turtle.Turtle()
    returns.hideturtle()
    turtle.addshape("returnbutton1.gif")
    returns.penup()
    returns.shape("returnbutton1.gif")
    returns.hideturtle()
    returns.goto(-300, -260)
    returns.showturtle()
    returns.onclick(questmap)
    searchC = turtle.Turtle()
    searchC.hideturtle()
    turtle.addshape("SearchC.gif")
    searchC.penup()
    searchC.shape("SearchC.gif")
    searchC.hideturtle()
    searchC.goto(300, -250)
    searchC.showturtle()
    searchC.onclick(searchinput2)
  if txt1 == "3":
    screen.clearscreen()
    screen.bgpic("13.gif")
    returns = turtle.Turtle()
    returns.hideturtle()
    turtle.addshape("returnbutton1.gif")
    returns.penup()
    returns.shape("returnbutton1.gif")
    returns.hideturtle()
    returns.goto(-300, -260)
    returns.showturtle()
    returns.onclick(questmap)
    searchC = turtle.Turtle()
    searchC.hideturtle()
    turtle.addshape("SearchC.gif")
    searchC.penup()
    searchC.shape("SearchC.gif")
    searchC.hideturtle()
    searchC.goto(300, -260)
    searchC.showturtle()
    searchC.onclick(searchinput2)
  if txt1 == "4":
    screen.clearscreen()
    screen.bgpic("14.gif")
    returns = turtle.Turtle()
    returns.hideturtle()
    turtle.addshape("returnbutton1.gif")
    returns.penup()
    returns.shape("returnbutton1.gif")
    returns.hideturtle()
    returns.goto(-300, -260)
    returns.showturtle()
    returns.onclick(questmap)
    searchC = turtle.Turtle()
    searchC.hideturtle()
    turtle.addshape("SearchC.gif")
    searchC.penup()
    searchC.shape("SearchC.gif")
    searchC.hideturtle()
    searchC.goto(300, -260)
    searchC.showturtle()
    searchC.onclick(searchinput2)
  if txt1 == "5":
    screen.clearscreen()
    screen.bgpic("15.gif")
    returns = turtle.Turtle()
    returns.hideturtle()
    turtle.addshape("returnbutton1.gif")
    returns.penup()
    returns.shape("returnbutton1.gif")
    returns.hideturtle()
    returns.goto(-300, -260)
    returns.showturtle()
    returns.onclick(questmap)
    searchC = turtle.Turtle()
    searchC.hideturtle()
    turtle.addshape("SearchC.gif")
    searchC.penup()
    searchC.shape("SearchC.gif")
    searchC.hideturtle()
    searchC.goto(300, -260)
    searchC.showturtle()
    searchC.onclick(searchinput2)
  if txt1 == "6":
    screen.clearscreen()
    screen.bgpic("16.gif")
    returns = turtle.Turtle()
    returns.hideturtle()
    turtle.addshape("returnbutton1.gif")
    returns.penup()
    returns.shape("returnbutton1.gif")
    returns.hideturtle()
    returns.goto(-300, -260)
    returns.showturtle()
    returns.onclick(questmap)
    searchC = turtle.Turtle()
    searchC.hideturtle()
    turtle.addshape("SearchC.gif")
    searchC.penup()
    searchC.shape("SearchC.gif")
    searchC.hideturtle()
    searchC.goto(300, -260)
    searchC.showturtle()
    searchC.onclick(searchinput2)
  
def choose2(x,y):
  choice2 = turtle.Turtle()
  choice2.showturtle()
  screen.clearscreen()
  screen.bgcolor("purple")
  screen.bgpic("Search22.gif")
  search = turtle.Turtle()
  turtle.addshape("searchbar1.gif")
  search.penup()
  search.shape("searchbar1.gif")
  search.hideturtle()
  search.goto(0, 50)
  search.showturtle()
  search.onclick(searchinput)
  returns = turtle.Turtle()
  returns.hideturtle()
  turtle.addshape("returnbutton1.gif")
  returns.penup()
  returns.shape("returnbutton1.gif")
  returns.hideturtle()
  returns.goto(300, -250)
  returns.showturtle()
  returns.onclick(questmap)

def choose3(x,y):
  choice3 = turtle.Turtle()
  choice3.showturtle()
  screen.clearscreen()
  screen.bgcolor("white")
  email = turtle.Turtle()
  turtle.addshape("emails.gif")
  email.shape("emails.gif")
  email.penup()
  email.goto(0,200)
  email.showturtle()
  emailbox = turtle.Turtle()
  turtle.addshape("mailbox1.gif")
  emailbox.shape("mailbox1.gif")
  emailbox.penup()
  emailbox.goto(0,-20)
  emailbox.showturtle()
  emailbox.onclick(emails)

def choose4(x,y):
  choice4 = turtle.Turtle()
  choice4.hideturtle()
  screen.clearscreen()
  screen.bgcolor("white")
  courselogo = turtle.Turtle()
  courselogo.hideturtle()
  turtle.addshape("level1course.gif")
  courselogo.hideturtle()
  courselogo.penup()
  courselogo.shape("level1course.gif")
  courselogo.hideturtle()
  courselogo.goto(0, 600)
  courselogo.showturtle()
  courselogo.speed("fast")
  courselogo.goto(0, 160)
  startcourse = turtle.Turtle()
  turtle.addshape("start course.gif")
  startcourse.penup()
  startcourse.shape("start course.gif")
  startcourse.hideturtle()
  startcourse.goto(200, 10)
  startcourse.showturtle()
  startcourse.onclick(course_start)

def questmap(x,y):
  screen.clearscreen()
  screen.bgpic("Questmap.gif")
  screen.bgcolor("white")
  newtext1 = turtle.Turtle()
  newtext1.penup()
  newtext1.hideturtle()
  newtext1.goto(-250, 200)
  newtext1.color("black")
  newtext1.write("Motorola Legends Dashboard", False, align='center', font=('Arial', 15, 'bold'))
  maplegend = turtle.Turtle()
  maplegend.hideturtle()
  turtle.addshape("number11.gif")
  maplegend.penup()
  maplegend.shape("number11.gif")
  maplegend.hideturtle()
  maplegend.goto(-390, -230)
  maplegend.showturtle()
  pandalf = turtle.Turtle()
  pandalf.hideturtle()
  turtle.addshape("panda4.gif")
  pandalf.penup()
  pandalf.shape("panda4.gif")
  pandalf.hideturtle()
  pandalf.goto(390, 230)
  pandalf.showturtle()
  level_list =["button1.gif", "button2.gif", "button3.gif", "button4.gif"]
  maplevels = []
  yaxis = [30, -110, -10, 65]
  x = -200
  for i in range(len(level_list)):
    turtle.addshape(level_list[i])
    quest = turtle.Turtle()
    quest.hideturtle()
    maplevels.append(quest)
    quest.shape(level_list[i])
    quest.penup()
    quest.goto(x, yaxis[i])
    quest.showturtle()
    x = x + 120
  while True:
    maplevels[0].onclick(choose1)
    maplevels[1].onclick(choose2)
    maplevels[2].onclick(choose3)
    maplevels[3].onclick(choose4)

screen.listen()

screen.onclick(questmap)

turtle.mainloop() # uncomment once you start doing turtle drawing